# Generated by Django 4.2.2 on 2023-06-22 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_voter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(default='', upload_to='home/media')),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Voter',
        ),
    ]
